"""Apply an AI fix to the source repo: create branch, commit, push, open PR."""

import logging
import os
import re
import subprocess

import httpx

logger = logging.getLogger(__name__)


def _run_git(workspace: str, *args: str) -> str:
    """Run a git command in the workspace directory."""
    result = subprocess.run(
        ["git", *args],
        cwd=workspace,
        capture_output=True,
        text=True,
        timeout=30,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"git {' '.join(args)} failed (rc={result.returncode}): "
            f"stderr={result.stderr.strip()} stdout={result.stdout.strip()}"
        )
    return result.stdout.strip()


def _parse_github_owner_repo(source_url: str) -> tuple[str, str] | None:
    """Extract (owner, repo) from a GitHub URL."""
    m = re.search(r"github\.com[/:]([^/]+)/([^/.]+?)(?:\.git)?$", source_url)
    if m:
        return m.group(1), m.group(2)
    return None


def _apply_code_to_file(
    workspace: str, file_path: str, line_start: int | None,
    fixed_code: str, line_end: int | None = None,
    original_snippet: str = "",
):
    """Replace the vulnerable code in the file with the fixed code.

    Uses the original line range (line_start..line_end) to determine how many
    lines to replace — NOT the number of lines in the fix — so that files are
    not corrupted when the AI adds or removes lines.

    When line_start is unavailable, tries to locate the original snippet in the
    file and replace it in-place so the rest of the file is preserved.
    """
    full_path = os.path.join(workspace, file_path)
    if not os.path.isfile(full_path):
        raise FileNotFoundError(f"File not found in workspace: {file_path}")

    with open(full_path, encoding="utf-8", errors="replace") as f:
        lines = f.readlines()

    fix_lines = fixed_code.split("\n")

    if line_start and line_start > 0:
        start_idx = line_start - 1  # 0-indexed
        if line_end and line_end >= line_start:
            orig_span = line_end - line_start + 1
        else:
            orig_span = 1
        end_idx = min(start_idx + orig_span, len(lines))
        new_lines = (
            lines[:start_idx]
            + [line + "\n" if not line.endswith("\n") else line for line in fix_lines]
            + lines[end_idx:]
        )
    elif original_snippet:
        # No line info — find the original snippet in the file and replace it
        content = "".join(lines)
        snippet_stripped = original_snippet.strip()
        if snippet_stripped and snippet_stripped in content:
            fixed_stripped = fixed_code.strip()
            content = content.replace(snippet_stripped, fixed_stripped, 1)
            new_lines = content.splitlines(keepends=True)
        else:
            # Snippet not found — try line-by-line match on the first line
            first_line = snippet_stripped.split("\n")[0].strip()
            matched = False
            for i, line in enumerate(lines):
                if first_line and first_line in line:
                    snippet_lines = original_snippet.strip().split("\n")
                    span = len(snippet_lines)
                    end_idx = min(i + span, len(lines))
                    new_lines = (
                        lines[:i]
                        + [line + "\n" if not line.endswith("\n") else line for line in fix_lines]
                        + lines[end_idx:]
                    )
                    matched = True
                    break
            if not matched:
                raise ValueError(
                    f"Cannot locate original code in {file_path}. "
                    "Fix must be applied manually."
                )
    else:
        # No line info and no snippet match — the fixed_code is the entire file
        # (generated by FIX_PROMPT_FULL_FILE). Write it directly.
        new_lines = [line + "\n" if not line.endswith("\n") else line for line in fix_lines]

    with open(full_path, "w", encoding="utf-8") as f:
        f.writelines(new_lines)


def apply_fix_and_create_pr(finding, github_token: str = "") -> dict:
    """Apply a fix to the repo, push a branch, and create a GitHub PR.

    Returns dict with keys: pr_url, branch_name, commit_sha.
    """
    if not finding.fix_generated_at or not finding.fixed_code:
        raise ValueError("No AI fix available. Generate a fix first.")

    if finding.fix_pr_url:
        return {"pr_url": finding.fix_pr_url, "branch_name": "", "commit_sha": "", "cached": True}

    scan = finding.scan
    workspace = scan.workspace_path
    if not workspace or not os.path.isdir(workspace):
        raise ValueError("Scan workspace no longer available.")

    if not github_token:
        raise ValueError("Token GitHub manquant. Connecte-toi via GitHub OAuth pour créer des PRs.")

    source_url = scan.source_url
    gh_info = _parse_github_owner_repo(source_url)
    if not gh_info:
        raise ValueError("Only GitHub repositories are supported for PR creation.")
    owner, repo = gh_info

    # Build a slug for the branch name
    slug = re.sub(r"[^a-z0-9]+", "-", finding.title.lower())[:40].strip("-")
    branch_name = f"fix/{slug}-{str(finding.id)[:8]}"

    # Configure git identity
    _run_git(workspace, "config", "user.email", "securescan-bot@users.noreply.github.com")
    _run_git(workspace, "config", "user.name", "SecureScan Bot")

    # Make sure we're on a clean main branch first
    try:
        _run_git(workspace, "checkout", "main")
    except RuntimeError:
        try:
            _run_git(workspace, "checkout", "master")
        except RuntimeError:
            pass  # stay on whatever branch

    # Create fix branch
    try:
        _run_git(workspace, "checkout", "-b", branch_name)
    except RuntimeError:
        # Branch might already exist
        _run_git(workspace, "checkout", branch_name)

    # Apply the fix to the file
    _apply_code_to_file(
        workspace, finding.file_path, finding.line_start, finding.fixed_code,
        line_end=finding.line_end, original_snippet=finding.code_snippet or "",
    )

    # Stage and commit
    _run_git(workspace, "add", finding.file_path)
    commit_msg = (
        f"fix: {finding.title}\n\n"
        f"OWASP: {finding.owasp_category}\n"
        f"Severity: {finding.severity}\n"
        f"Tool: {finding.tool}\n\n"
        f"AI-generated fix by SecureScan"
    )
    # Check if there are staged changes before committing
    diff_status = _run_git(workspace, "diff", "--cached", "--name-only")
    if diff_status:
        msg_file = os.path.join(workspace, ".git", "COMMIT_MSG")
        with open(msg_file, "w") as f:
            f.write(commit_msg)
        try:
            _run_git(workspace, "commit", "-F", msg_file)
        finally:
            try:
                os.unlink(msg_file)
            except OSError:
                pass
    else:
        logger.info("No staged changes — fix already applied on branch %s", branch_name)
    commit_sha = _run_git(workspace, "log", "-1", "--format=%H")

    # Push using GIT_ASKPASS to inject the token via env — never written to .git/config.
    # This avoids the race condition where a failure between set-url and restore
    # would leave the token on disk for up to 48 hours.
    import tempfile  # noqa: PLC0415

    askpass_script = None
    try:
        # Create a temporary askpass script that echoes the token
        askpass_script = tempfile.NamedTemporaryFile(
            mode="w", suffix=".sh", delete=False, dir=workspace,
        )
        askpass_script.write(
            f'#!/bin/sh\n'
            f'case "$1" in\n'
            f'  *Username*) echo "x-access-token" ;;\n'
            f'  *) echo "{github_token}" ;;\n'
            f'esac\n'
        )
        askpass_script.close()
        os.chmod(askpass_script.name, 0o700)

        push_env = {
            **os.environ,
            "GIT_ASKPASS": askpass_script.name,
            "GIT_TERMINAL_PROMPT": "0",
        }

        push_url = f"https://github.com/{owner}/{repo}.git"
        result = subprocess.run(
            ["git", "push", push_url, f"HEAD:{branch_name}"],
            cwd=workspace,
            capture_output=True,
            text=True,
            timeout=30,
            env=push_env,
        )
        if result.returncode != 0:
            raise ValueError(f"Failed to push branch: {result.stderr.strip()}")
    finally:
        # Always delete the askpass script — token never stays on disk
        if askpass_script:
            try:
                os.unlink(askpass_script.name)
            except OSError:
                pass

    # Create PR via GitHub API
    pr_body = (
        f"## Security Fix\n\n"
        f"**Vulnerability:** {finding.title}\n"
        f"**OWASP:** {finding.owasp_category}\n"
        f"**Severity:** {finding.severity}\n"
        f"**Tool:** {finding.tool}\n"
        f"**File:** `{finding.file_path}`:{finding.line_start or '?'}\n\n"
        f"### AI Explanation\n{finding.fix_explanation}\n\n"
        f"---\n*Generated automatically by SecureScan AI*"
    )

    try:
        resp = httpx.post(
            f"https://api.github.com/repos/{owner}/{repo}/pulls",
            headers={
                "Authorization": f"Bearer {github_token}",
                "Accept": "application/vnd.github+json",
            },
            json={
                "title": f"fix: {finding.title}",
                "body": pr_body,
                "head": branch_name,
                "base": "main",
            },
            timeout=15,
        )
        if resp.status_code == 422:
            # Try with master as base
            resp = httpx.post(
                f"https://api.github.com/repos/{owner}/{repo}/pulls",
                headers={
                    "Authorization": f"Bearer {github_token}",
                    "Accept": "application/vnd.github+json",
                },
                json={
                    "title": f"fix: {finding.title}",
                    "body": pr_body,
                    "head": branch_name,
                    "base": "master",
                },
                timeout=15,
            )
        resp.raise_for_status()
        pr_data = resp.json()
        pr_url = pr_data["html_url"]
    except httpx.HTTPStatusError as exc:
        logger.error("GitHub API error creating PR: %s — %s", exc.response.status_code, exc.response.text)
        raise ValueError(f"GitHub API error: {exc.response.status_code}") from exc

    # Save PR URL on finding
    finding.fix_pr_url = pr_url
    finding.save(update_fields=["fix_pr_url"])

    return {
        "pr_url": pr_url,
        "branch_name": branch_name,
        "commit_sha": commit_sha,
        "cached": False,
    }
