# Generated by Django 6.0.3 on 2026-03-05 13:57

from django.db import migrations, models

import apps.accounts.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude')], default='gemini', max_length=20),  # noqa: E501
        ),
        migrations.AddField(
            model_name='userprofile',
            name='anthropic_api_key',
            field=apps.accounts.fields.EncryptedCharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_api_key',
            field=apps.accounts.fields.EncryptedCharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_access_token',
            field=apps.accounts.fields.EncryptedCharField(blank=True, default='', max_length=512),
        ),
    ]
